apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
  namespace: mrseyh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: first-deployment
  template:
    metadata:
      labels:
        app: first-deployment
    spec:
      containers:
      - name: first-deployment
        image: mrseyh/devopstask:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: first-service
  namespace: mrseyh
spec:
  selector:
    app: first-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: first-ingress
  namespace: mrseyh
spec:
  rules:
    - host: mrseyh-dart.fria.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: first-service
                port:
                  number: 80
